services:
  schedule-worker:
    image: aggregator/app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: aggregator-schedule-worker
    command: php artisan schedule:work
    depends_on:
      - app
    volumes:
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:rw
  node:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

volumes:
  storage:
  public:
