global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - localhost:9090

  - job_name: "node"
    static_configs:
      - targets:
        - node:9100
    metrics_path: "/metrics"

  - job_name: "app"
    static_configs:
      - targets:
        - 192.168.56.10:80
    metrics_path: "/prometheus"

  - job_name: "app-node"
    static_configs:
      - targets:
        - 192.168.56.10:9100
    metrics_path: "/metrics"

  - job_name: "mysql-node"
    static_configs:
      - targets:
        - 192.168.56.40:9100
    metrics_path: "/metrics"

  - job_name: "queue-node"
    static_configs:
      - targets:
        - 192.168.56.20:9100
    metrics_path: "/metrics"

  - job_name: "scheduler-node"
    static_configs:
      - targets:
        - 192.168.56.30:9100
    metrics_path: "/metrics"