global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - localhost:9090

  - job_name: "node"
    static_configs:
      - targets:
        - node:9100
    metrics_path: "/metrics"

  - job_name: "app"
    static_configs:
      - targets:
        - app:9000
    metrics_path: "/prometheus"

  - job_name: "nginx"
    static_configs:
      - targets:
        - nginx:80
        - nginx:443
    metrics_path: "/prometheus"