#!/bin/bash

main() {
    if [ "$IS_WORKER" = "true" ]; then
        exec "$@"
    else
        prepare_file_permissions
        run_npm_build
        prepare_storage
        make_env
        #wait_for_db
        run_migrations
        optimize_app
        run_server "$@"
    fi
}

prepare_file_permissions() {
    chmod a+x ./artisan
}

run_npm_build() {
    echo "Installing NPM dependencies"
    if [ -f "package.json" ]; then
        echo "Running NPM clean install"
        npm ci

        echo "Running NPM build"
        npm run build
    else
        echo "No package.json found, skipping NPM build"
    fi
}

prepare_storage() {
    # Create required directories for Laravel

    mkdir -p /usr/share/nginx/html/storage/framework/cache/data
    mkdir -p /usr/share/nginx/html/storage/framework/sessions
    mkdir -p /usr/share/nginx/html/storage/framework/views

    # Set permissions for the storage directory
    chown -R www-data:www-data /usr/share/nginx/html/storage
    chmod -R 775 /usr/share/nginx/html/storage

    # Ensure the symlink exists
    php artisan storage:link
}

wait_for_db() {
    echo $DB_HOST
    # Wait for the database to be ready
    echo "Waiting for the database to be ready..."
    while ! mysqladmin ping -h "$DB_HOST" --silent; do
        sleep 1
    done
    echo "Database is ready!"
}

make_env() {
    cp .env.example .env
    chmod 775 .env
    ./artisan key:generate
}

run_migrations() {
    ./artisan migrate --force
}

#Look into how to run the optimize command in a production environment
optimize_app() {
    ./artisan optimize:clear
    ./artisan optimize
}

# Author used /usr/local/bin/docker-php-entrypoint as a reference. Why?
run_server() {
    exec /usr/local/bin/docker-php-entrypoint "$@"
}

main "$@"
